### ISSUE TITLE
Jitsi Meet integration

### ISSUE THREAD

**Issue by cristobalcampr** [CamprGmbH/campr#65]
When creating a new meeting and sending the meeting invitation, a link to a [Jitsi meeting](https://jitsi.org/jitsi-meet/) should be sent automatically.

The corresponding function in google meet serves as a model.

![meeting](https://user-images.githubusercontent.com/63307779/85206241-0658d880-b321-11ea-94b0-2ff7f11c6946.PNG)

**Comment by cristobalcampr** [comment]
- JITSI server on-premise at CAMPR already running

**Comment by cristobalcampr** [comment]
Jitsi-Server CAMPR: https://jitsi.campr.wiki

**Comment by CAMPR-Manuel** [comment]
With this ticket we want to integrate a video-call function for meeting participants in CAMPR. For the video-call we use our own 'Jitsi-Application' which can be accessed via the following link: 

https://jitsi.campr.biz

Following the way meetings are structured in CAMPR, we need a dedicated 'Jitsi-Link' for each distribution list in each project in CAMPR. Therefor we suggest the following approach to create unique "video-call-links" for each distribution list: 

https://jitsi.campr.biz/    +    'WorkspaceID'+'ProjectID'+'DistributionListName'

This link needs to be generated within the CAMPR application while creating a new meeting. The link shall appear for the user as followed: 

- Meetings overview in CAMPR after the meeting was created
- Email-Body after meeting invite is sent out
- Within the meeting invitation which is attached to the email invite so that the link appears after adding the invite to user calendar.

**Comment by maxlenash** [comment]
done and merged to develop

**Comment by HannesCAMPR** [comment]
Testing:
1. Create meeting in WS1 – Project 1 – default distribution list
2. create meeting in WS1 – project 1 – different distribution list
3. create meeting in WS1 – project 2 – default distribution list
4. create meeting in WS2 – project 1 – default distribution list
5. new user, new workspace, new project and default distribution list
Feedback:
Tests 1-3 were successful, test 4 produced the same jitsi link as in step 1 and is therefore not unique anymore. Test 5 also reproduced the same jitsi-link (All ending with 111)

**Comment by maxlenash** [comment]
fixed in local
